token: <your-bot-token>
removeExceptionChannels: false
privateVoiceCategoryId:
privateVoiceChannelId:
privateVoiceChannelName: "點我建立私人頻道"
noPermissionTitle: "您的權限不足!"
noPermissionDescription: "您沒有權限執行此指令!"
noPermissionColor: "#AA0000"
noVoiceChannelColor: "#AA0000"
noVoiceChannelTitle: "你需要有一個語音頻道!"
noVoiceChannelDescription: "請先建立一個語音頻道再執行此指令!"
successColor: "#008000"
errorColor: "#AA0000"
successTitle: "成功!"
errorTitle: "錯誤!"
commandToBotError: "你無法對機器人執行指令!"
commandSetCreateChannelSuccess: "成功設定頻道!"
commandSetCreateChannelError: "設定頻道時發生錯誤 請確認您指定頻道是否為語音頻道!"
commandSetCreateCategorySuccess: "成功設定分類!"
commandSetCreateCategoryError: "設定分類時發生錯誤 請確認您指定類型是否為分類!"
commandInviteSelfError: "你無法邀請自己!"
commandInviteSuccess: "成功邀請成員!"
commandKickSelfError: "你無法踢出自己!"
commandKickPublicError: "你只能在私人頻道踢出其他成員!"
commandKickNotInvitedError: "對方不在此頻道的邀請列表!"
commandInviteAlreadyInvitedError: "對方已經在此頻道的邀請列表!"
commandKickSuccess: "成功踢出成員!"
commandRenameSuccess: "成功更改頻道名稱!"
commandTransferSelfError: "你已經是此語音頻道的擁有者!"
commandTransferSuccess: "成功轉移頻道擁有權!"
commandTransferTargetError: "對方已經擁有一個語音頻道!"
commandToggleVisibilitySuccess: "成功切換頻道可見性!"
commandCloseSuccess: "成功關閉頻道!"
footer: "Powered by Nontage"
footerIcon: "https://cdn.discordapp.com/avatars/810170073239126066/98c4e35237d5ab7ff452e7dcd71e4a75.png?size=2048&quality=lossless"
privateVoiceChannelSuffix: "的私人頻道"